# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://github.com/mstephania/Portfolio/
title: Mindy Munoz
email: mindystephania@gmail.com
author: Mindy
description: "MyProfile's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/mstephania
  - icon: envelope-o
    title: email
    url: mailto:mindystephania@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/mindy-m-miranda/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyCV.pdf
  - icon: google
    title: Google Scholar
    url: https://scholar.google.com/citations?user=vdIn8RcAAAAJ&hl=en

